<?php

$front = Zend_Controller_Front::getInstance();
$bootstrap = $front->getParam('bootstrap');
$resource = $bootstrap->getPluginResource('db');
$dbAdapter = $resource->getDbAdapter();
$statement = $dbAdapter->query("SELECT * FROM `menu`");
$menuArray = $statement->fetchAll();

?>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Menu</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">ZendCMS</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach($menuArray as $menuItem): ?>
                    <li class="<?php if($menuItem['label'] == 'Home'): ?>active<?php endif;?>">
                        <a href="<?php echo $menuItem['href'] ?>"  title="<?php echo $menuItem['title'];?>" alt="<?php echo $menuItem['alt']?>">
                            <?php echo $menuItem['label']; ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
                    <li><a href="/content/"><span class="glyphicon glyphicon-hand-right"></span> Admin</a></li>
                <?php endif; ?>
                <li>
                    <?php
                        if(!Zend_Auth::getInstance()->hasIdentity())
                        echo '<a href="/login/index">Login</a>';
                        else
                        echo '<a href="/login/logout">Logout</a>';
                    ?>
                </li>
            </ul>
        </div>
    </div>
</div>
