<div class="row">
    <h2 class="col-sm-4 col-md-4 col-lg-4 col-lg-offset-5 col-md-offset-5 col-sm-offset-5">Logging In</h2>
</div>
<?php if($this->errorMessage != ""): ?>
    <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4 col-lg-offset-4 col-md-offset-4 col-sm-offset-4 text-center">
            <div class="alert alert-danger">
                <?php echo $this->errorMessage; ?>
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 text-center">
        <div id="login">
            <?php echo $this->loginForm ?><br/>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2 col-sm-offset-4 col-lg-offset-4 col-md-offset-4 text-center">
        <a href="account/forgot">Wachtwoord vergeten</a>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2 text-center">
        <a href="account/new">Nieuw account</a>
    </div>
</div>
