<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text-html;charset=utf-8');
    $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
    $this->headMeta()->appendName('description', 'CMS created with Zend using Twitter Bootstrap');
    $this->headMeta()->appendName('author', 'Koen Hendriks');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Zend CMS');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()
        ->appendStylesheet($this->baseUrl.'/css/main.css')
        ->appendStylesheet($this->baseUrl.'/css/bootstrap.min.css')
        ->headLink(
                    array(
                            'rel' => 'icon',
                            'href' => $this->baseUrl().'/icon/favicon.ico',
                            'type' => 'image/x-icon', 'PREPEND'
                    )
        ); ?>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <base href="<?php echo $this->baseUrl; ?>/">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Menu</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">ZendCMS</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/content/"><span class="glyphicon glyphicon-hand-right"></span> Admin</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <?php echo $this->layout()->content; ?>
</div>

</body>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="<?php echo $this->baseUrl() ?>js/bootstrap.min.js"></script>
</body>
</html>